export const TRANSITION_PROGRESS_START = 0.001;
export const TRANSITION_PROGRESS_END = 0.999;

const INPUT_RANGE = [0, TRANSITION_PROGRESS_START,
  TRANSITION_PROGRESS_START + TRANSITION_PROGRESS_START,
  TRANSITION_PROGRESS_END - TRANSITION_PROGRESS_START,
  TRANSITION_PROGRESS_END, 1];

export const ORIGINAL_VIEWS_VISIBILITY_INPUT_RANGE_ANIM_IN = INPUT_RANGE;
export const ORIGINAL_VIEWS_VISIBILITY_OUTPUT_RANGE_ANIM_IN = [1, 1, 0, 0, 0, 0];

export const ORIGINAL_VIEWS_VISIBILITY_INPUT_RANGE_ANIM_OUT = INPUT_RANGE;
export const ORIGINAL_VIEWS_VISIBILITY_OUTPUT_RANGE_ANIM_OUT = [0, 0, 0, 0, 1, 1];

export const OVERLAY_VIEWS_VISIBILITY_INPUT_RANGE = INPUT_RANGE;
export const OVERLAY_VIEWS_VISIBILITY_OUTPUT_RANGE = [0, 1, 1, 1, 1, 0];

