export const ORIGINAL_VIEWS_VISIBILITY_INPUT_RANGE = [0, 0.9999, 0.9999, 1];
export const ORIGINAL_VIEWS_VISIBILITY_OUTPUT_RANGE = [0, 0, 1, 1];

export const TRANSITION_PROGRESS_START = 0.0001;
export const TRANSITION_PROGRESS_END = 0.9999;

export const OVERLAY_VIEWS_VISIBILITY_INPUT_RANGE = 
  [0, TRANSITION_PROGRESS_START, TRANSITION_PROGRESS_END, 1];
  
export const OVERLAY_VIEWS_VISIBILITY_OUTPUT_RANGE = [0, 1, 1, 0];

